// src/lib/affiliate-programs.ts

import type {
  AffiliateProgram,
  BrandDeal,
} from "@/types/brand-deals";

// ---------------------------------------------------------------------------
// Curated Affiliate Programs (~73 real programs)
// ---------------------------------------------------------------------------

export const AFFILIATE_PROGRAMS: AffiliateProgram[] = [
  // ── E-Commerce: Fashion ─────────────────────────────────────────────
  {
    id: "prog-tiktok-shop",
    name: "TikTok Shop",
    logo: "https://logo.clearbit.com/tiktok.com",
    description:
      "Promote products from TikTok Shop's Open Collaboration marketplace. Earn commission on every sale through your content.",
    commissionRange: "5–20%",
    type: "ecommerce",
    platforms: ["tiktok"],
    signUpUrl: "https://seller.tiktok.com/",
    category: "fashion",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-amazon-influencer",
    name: "Amazon Influencer Program",
    logo: "https://logo.clearbit.com/amazon.com",
    description:
      "Create your own Amazon storefront to curate product recommendations. Earn commissions plus storefront bonuses.",
    commissionRange: "1–10% + storefront",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.amazon.com/shop/info",
    category: "fashion",
    barrier: "open",
  },
  {
    id: "prog-walmart-creator",
    name: "Walmart Creator",
    logo: "https://logo.clearbit.com/walmart.com",
    description:
      "Promote Walmart products with no minimum follower requirement. Up to 20% commission with native social commerce features.",
    commissionRange: "Up to 20%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://creator.walmart.com/",
    category: "fashion",
    barrier: "open",
    isNew: true,
  },
  {
    id: "prog-shopify-collabs",
    name: "Shopify Collabs",
    logo: "https://logo.clearbit.com/shopify.com",
    description:
      "Connect with thousands of Shopify brands looking for creators. Custom commission rates negotiated per brand.",
    commissionRange: "Custom",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.shopify.com/collabs",
    category: "fashion",
    barrier: "open",
  },
  {
    id: "prog-asos",
    name: "ASOS",
    logo: "https://logo.clearbit.com/asos.com",
    description:
      "Promote 850+ brands on ASOS. Earn commission on fashion, beauty, and lifestyle products for 20-something audiences.",
    commissionRange: "5–6%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.asos.com/affiliate-programme/",
    category: "fashion",
    barrier: "approval",
  },
  {
    id: "prog-shein",
    name: "SHEIN",
    logo: "https://logo.clearbit.com/shein.com",
    description:
      "Promote affordable fashion from SHEIN's massive catalog. Earn commission on every sale plus exclusive creator discounts.",
    commissionRange: "10–20%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://us.shein.com/affiliate-program.html",
    category: "fashion",
    barrier: "open",
  },
  {
    id: "prog-prettylittlething",
    name: "PrettyLittleThing",
    logo: "https://logo.clearbit.com/prettylittlething.com",
    description:
      "Fast-fashion affiliate program with high conversion rates. Earn commission promoting trending styles and celeb collabs.",
    commissionRange: "5–10%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.prettylittlething.com/affiliates",
    category: "fashion",
    barrier: "approval",
  },
  {
    id: "prog-revolve",
    name: "Revolve",
    logo: "https://logo.clearbit.com/revolve.com",
    description:
      "Premium fashion affiliate program featuring designer and contemporary brands. Known for strong creator partnerships.",
    commissionRange: "5%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.revolve.com/content/affiliates",
    category: "fashion",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-princess-polly",
    name: "Princess Polly",
    logo: "https://logo.clearbit.com/princesspolly.com",
    description:
      "Australian fashion brand popular with Gen Z creators. Earn commission on trendy, affordable pieces.",
    commissionRange: "8–15%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://us.princesspolly.com/pages/affiliates",
    category: "fashion",
    barrier: "approval",
    isNew: true,
  },
  {
    id: "prog-nike",
    name: "Nike",
    logo: "https://logo.clearbit.com/nike.com",
    description:
      "Promote Nike sneakers, apparel, and gear. One of the most recognized brands globally with strong conversion rates.",
    commissionRange: "Up to 11%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.nike.com/affiliate",
    category: "fashion",
    barrier: "approval",
  },
  {
    id: "prog-adidas",
    name: "Adidas",
    logo: "https://logo.clearbit.com/adidas.com",
    description:
      "Promote Adidas sportswear, sneakers, and collaborations. Competitive commissions on a globally trusted brand.",
    commissionRange: "7%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.adidas.com/us/affiliate-program",
    category: "fashion",
    barrier: "approval",
  },

  // ── E-Commerce: Tech ────────────────────────────────────────────────
  {
    id: "prog-amazon-associates",
    name: "Amazon Associates",
    logo: "https://logo.clearbit.com/amazon.com",
    description:
      "Link to any product on Amazon and earn commissions on qualifying purchases. The world's largest affiliate program.",
    commissionRange: "1–20%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://affiliate-program.amazon.com/",
    category: "tech",
    barrier: "open",
    isFeatured: true,
  },
  {
    id: "prog-best-buy",
    name: "Best Buy",
    logo: "https://logo.clearbit.com/bestbuy.com",
    description:
      "Promote consumer electronics, appliances, and tech gadgets from Best Buy. Trusted brand with high average order values.",
    commissionRange: "1–7%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.bestbuy.com/site/affiliate-program/",
    category: "tech",
    barrier: "approval",
  },
  {
    id: "prog-newegg",
    name: "Newegg",
    logo: "https://logo.clearbit.com/newegg.com",
    description:
      "Tech-focused retailer for PC components, gaming gear, and electronics. Popular with tech-savvy creator audiences.",
    commissionRange: "2.5–5%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.newegg.com/affiliates",
    category: "tech",
    barrier: "approval",
  },
  {
    id: "prog-bh-photo",
    name: "B&H Photo",
    logo: "https://logo.clearbit.com/bhphotovideo.com",
    description:
      "The go-to for camera gear, lighting, and creator equipment. High average order values and trusted by content creators.",
    commissionRange: "2–8%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.bhphotovideo.com/find/affiliateProgram.jsp",
    category: "tech",
    barrier: "approval",
  },

  // ── E-Commerce: Beauty ──────────────────────────────────────────────
  {
    id: "prog-sephora-storefront",
    name: "Sephora My Storefront",
    logo: "https://logo.clearbit.com/sephora.com",
    description:
      "Curate and share Sephora products through your personal storefront. Earn 15% commission on all sales.",
    commissionRange: "15%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.sephora.com/beauty/affiliate-program",
    category: "beauty",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-ulta",
    name: "Ulta Beauty",
    logo: "https://logo.clearbit.com/ulta.com",
    description:
      "Largest beauty retailer in the US. Promote prestige and drugstore beauty brands with competitive commission rates.",
    commissionRange: "2–5%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.ulta.com/affiliate-program",
    category: "beauty",
    barrier: "approval",
  },
  {
    id: "prog-glossier",
    name: "Glossier",
    logo: "https://logo.clearbit.com/glossier.com",
    description:
      "Cult-favorite beauty brand with strong social media presence. Earn commission on skincare, makeup, and fragrance.",
    commissionRange: "10%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.glossier.com/affiliates",
    category: "beauty",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-colourpop",
    name: "ColourPop",
    logo: "https://logo.clearbit.com/colourpop.com",
    description:
      "Affordable, trend-driven makeup brand beloved by beauty creators. High conversion rates and frequent launches.",
    commissionRange: "5–8%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://colourpop.com/pages/affiliate-program",
    category: "beauty",
    barrier: "open",
  },
  {
    id: "prog-rare-beauty",
    name: "Rare Beauty",
    logo: "https://logo.clearbit.com/rarebeauty.com",
    description:
      "Selena Gomez's beauty line with a mission-driven brand story. Strong organic engagement and audience trust.",
    commissionRange: "5–10%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.rarebeauty.com/pages/affiliate-program",
    category: "beauty",
    barrier: "approval",
    isNew: true,
  },
  {
    id: "prog-elf-cosmetics",
    name: "e.l.f. Cosmetics",
    logo: "https://logo.clearbit.com/elfcosmetics.com",
    description:
      "Ultra-affordable beauty brand with viral TikTok products. High conversion rates and frequent product drops.",
    commissionRange: "5–9%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.elfcosmetics.com/affiliate-program",
    category: "beauty",
    barrier: "open",
  },
  {
    id: "prog-charlotte-tilbury",
    name: "Charlotte Tilbury",
    logo: "https://logo.clearbit.com/charlottetilbury.com",
    description:
      "Luxury beauty brand known for iconic products and glam aesthetics. Premium commissions on high-value orders.",
    commissionRange: "8%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.charlottetilbury.com/us/affiliate",
    category: "beauty",
    barrier: "approval",
  },

  // ── E-Commerce: Fitness ─────────────────────────────────────────────
  {
    id: "prog-gymshark",
    name: "Gymshark",
    logo: "https://logo.clearbit.com/gymshark.com",
    description:
      "Leading fitness apparel brand built by creators. Ambassador program with commissions, free products, and exclusive drops.",
    commissionRange: "6–10%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.gymshark.com/pages/affiliate",
    category: "fitness",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-alo-yoga",
    name: "Alo Yoga",
    logo: "https://logo.clearbit.com/aloyoga.com",
    description:
      "Premium yoga and athleisure brand popular with wellness creators. Earn commission on leggings, tops, and accessories.",
    commissionRange: "7%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.aloyoga.com/pages/affiliates",
    category: "fitness",
    barrier: "approval",
  },
  {
    id: "prog-lululemon",
    name: "Lululemon",
    logo: "https://logo.clearbit.com/lululemon.com",
    description:
      "Premium athletic apparel brand with a loyal community. Earn commission on yoga, running, and training gear.",
    commissionRange: "5–7%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://shop.lululemon.com/story/affiliate-program",
    category: "fitness",
    barrier: "approval",
  },
  {
    id: "prog-myprotein",
    name: "Myprotein",
    logo: "https://logo.clearbit.com/myprotein.com",
    description:
      "Europe's #1 sports nutrition brand. Earn commission on protein, supplements, and fitness accessories.",
    commissionRange: "8–12%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.myprotein.com/affiliate-programme.list",
    category: "fitness",
    barrier: "open",
  },
  {
    id: "prog-nike-training",
    name: "Nike Training",
    logo: "https://logo.clearbit.com/nike.com",
    description:
      "Promote Nike's training-specific gear, shoes, and apparel. Target fitness audiences with the world's top sports brand.",
    commissionRange: "Up to 11%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.nike.com/affiliate",
    category: "fitness",
    barrier: "approval",
  },
  {
    id: "prog-fabletics",
    name: "Fabletics",
    logo: "https://logo.clearbit.com/fabletics.com",
    description:
      "Subscription-based activewear brand co-founded by Kate Hudson. Earn on new member sign-ups and purchases.",
    commissionRange: "$10–$15 per lead",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.fabletics.com/affiliate",
    category: "fitness",
    barrier: "approval",
    isNew: true,
  },
  {
    id: "prog-ghost-lifestyle",
    name: "GHOST Lifestyle",
    logo: "https://logo.clearbit.com/ghostlifestyle.com",
    description:
      "Trendy supplement brand with licensed flavors and strong social presence. Popular with fitness and gaming creators.",
    commissionRange: "10–15%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.ghostlifestyle.com/pages/ambassador",
    category: "fitness",
    barrier: "approval",
  },
  {
    id: "prog-womens-best",
    name: "Women's Best",
    logo: "https://logo.clearbit.com/womensbest.com",
    description:
      "Women-focused fitness brand with supplements, activewear, and accessories. Strong Instagram creator community.",
    commissionRange: "10%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.womensbest.com/pages/ambassador",
    category: "fitness",
    barrier: "approval",
  },

  // ── E-Commerce: Gaming ──────────────────────────────────────────────
  {
    id: "prog-razer",
    name: "Razer",
    logo: "https://logo.clearbit.com/razer.com",
    description:
      "Leading gaming peripherals and lifestyle brand. Promote keyboards, mice, headsets, and gaming laptops.",
    commissionRange: "3–10%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.razer.com/affiliate-program",
    category: "gaming",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-steelseries",
    name: "SteelSeries",
    logo: "https://logo.clearbit.com/steelseries.com",
    description:
      "Premium gaming peripherals including headsets, keyboards, and mice. Trusted by esports pros and streamers.",
    commissionRange: "5–8%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://steelseries.com/pages/affiliate",
    category: "gaming",
    barrier: "approval",
  },
  {
    id: "prog-hyperx",
    name: "HyperX",
    logo: "https://logo.clearbit.com/hyperx.com",
    description:
      "HP's gaming brand known for headsets, keyboards, and microphones. Popular with content creators and streamers.",
    commissionRange: "3–5%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.hyperx.com/pages/affiliate",
    category: "gaming",
    barrier: "approval",
  },
  {
    id: "prog-secretlab",
    name: "Secretlab",
    logo: "https://logo.clearbit.com/secretlab.co",
    description:
      "Premium gaming chairs endorsed by top streamers and esports teams. High average order value for strong commissions.",
    commissionRange: "5–12%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://secretlab.co/pages/affiliate-program",
    category: "gaming",
    barrier: "approval",
    isNew: true,
  },
  {
    id: "prog-corsair",
    name: "Corsair",
    logo: "https://logo.clearbit.com/corsair.com",
    description:
      "PC components, peripherals, and streaming gear. Trusted name in gaming hardware with a broad product catalog.",
    commissionRange: "3–5%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.corsair.com/us/en/affiliate-program",
    category: "gaming",
    barrier: "approval",
  },
  {
    id: "prog-elgato",
    name: "Elgato",
    logo: "https://logo.clearbit.com/elgato.com",
    description:
      "Stream decks, capture cards, and lighting for content creators. The standard toolkit for streamers.",
    commissionRange: "4–6%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.elgato.com/us/en/affiliate",
    category: "gaming",
    barrier: "approval",
  },

  // ── E-Commerce: Food ────────────────────────────────────────────────
  {
    id: "prog-hellofresh",
    name: "HelloFresh",
    logo: "https://logo.clearbit.com/hellofresh.com",
    description:
      "America's most popular meal kit. Earn generous commissions on new subscriber sign-ups with high conversion rates.",
    commissionRange: "$10–$15 per signup",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.hellofresh.com/pages/affiliate",
    category: "food",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-factor",
    name: "Factor",
    logo: "https://logo.clearbit.com/factor75.com",
    description:
      "Chef-prepared, ready-to-eat meals delivered weekly. Popular with fitness and busy lifestyle creators.",
    commissionRange: "$10–$20 per signup",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.factor75.com/affiliate",
    category: "food",
    barrier: "approval",
  },
  {
    id: "prog-thrive-market",
    name: "Thrive Market",
    logo: "https://logo.clearbit.com/thrivemarket.com",
    description:
      "Membership-based online grocery for organic and natural products. Strong with wellness and healthy living audiences.",
    commissionRange: "$5–$40 per membership",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://thrivemarket.com/affiliate",
    category: "food",
    barrier: "approval",
  },
  {
    id: "prog-butcherbox",
    name: "ButcherBox",
    logo: "https://logo.clearbit.com/butcherbox.com",
    description:
      "Grass-fed, organic meat delivery subscription. Earn on new subscriber sign-ups with high lifetime value.",
    commissionRange: "$20 per signup",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.butcherbox.com/affiliate-program",
    category: "food",
    barrier: "approval",
  },
  {
    id: "prog-magic-spoon",
    name: "Magic Spoon",
    logo: "https://logo.clearbit.com/magicspoon.com",
    description:
      "High-protein, low-carb cereal brand popular on social media. One of the most promoted DTC food brands by creators.",
    commissionRange: "15–20%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.magicspoon.com/pages/affiliates",
    category: "food",
    barrier: "approval",
    isNew: true,
  },
  {
    id: "prog-daily-harvest",
    name: "Daily Harvest",
    logo: "https://logo.clearbit.com/daily-harvest.com",
    description:
      "Frozen smoothies, bowls, and plant-based meals delivered. Popular with health-conscious lifestyle creators.",
    commissionRange: "$10–$15 per signup",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.daily-harvest.com/affiliate",
    category: "food",
    barrier: "approval",
  },
  {
    id: "prog-athletic-greens",
    name: "AG1 (Athletic Greens)",
    logo: "https://logo.clearbit.com/drinkag1.com",
    description:
      "The most-sponsored supplement in podcasting and creator content. Premium greens powder with high payouts.",
    commissionRange: "$20–$50 per sale",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://drinkag1.com/partners",
    category: "food",
    barrier: "invite",
    isFeatured: true,
  },
  {
    id: "prog-liquid-iv",
    name: "Liquid I.V.",
    logo: "https://logo.clearbit.com/liquid-iv.com",
    description:
      "Hydration multiplier drink mix with strong social proof. Commonly promoted by fitness and wellness creators.",
    commissionRange: "10–15%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.liquid-iv.com/pages/affiliate",
    category: "food",
    barrier: "approval",
  },

  // ── E-Commerce: Travel ──────────────────────────────────────────────
  {
    id: "prog-booking",
    name: "Booking.com",
    logo: "https://logo.clearbit.com/booking.com",
    description:
      "World's largest online travel agency. Earn commission on hotels, flights, and car rentals booked through your links.",
    commissionRange: "25–40%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.booking.com/affiliate-program/",
    category: "travel",
    barrier: "open",
    isFeatured: true,
  },
  {
    id: "prog-expedia",
    name: "Expedia",
    logo: "https://logo.clearbit.com/expedia.com",
    description:
      "Promote hotels, vacation packages, and car rentals. Tiered commission structure rewards higher volume.",
    commissionRange: "2–6%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.expedia.com/affiliate",
    category: "travel",
    barrier: "approval",
  },
  {
    id: "prog-hostelworld",
    name: "Hostelworld",
    logo: "https://logo.clearbit.com/hostelworld.com",
    description:
      "Budget travel accommodation platform. Perfect for creators targeting Gen Z and backpacker audiences.",
    commissionRange: "$0.50–$1.50 per booking",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.hostelworld.com/affiliateprogram",
    category: "travel",
    barrier: "open",
  },
  {
    id: "prog-viator",
    name: "Viator",
    logo: "https://logo.clearbit.com/viator.com",
    description:
      "Book tours, activities, and experiences worldwide. Earn commission on experiences in 200+ countries.",
    commissionRange: "8%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.viator.com/affiliates",
    category: "travel",
    barrier: "open",
    isNew: true,
  },
  {
    id: "prog-get-your-guide",
    name: "GetYourGuide",
    logo: "https://logo.clearbit.com/getyourguide.com",
    description:
      "Book tours, attractions, and activities. Strong with travel vlog and adventure content creators.",
    commissionRange: "8%",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://partner.getyourguide.com/",
    category: "travel",
    barrier: "open",
  },
  {
    id: "prog-airbnb",
    name: "Airbnb",
    logo: "https://logo.clearbit.com/airbnb.com",
    description:
      "Refer new hosts and guests to Airbnb. Earn bonuses on first bookings and host sign-ups.",
    commissionRange: "$25–$250 per referral",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.airbnb.com/refer",
    category: "travel",
    barrier: "open",
  },

  // ── E-Commerce: Finance ─────────────────────────────────────────────
  {
    id: "prog-cash-app",
    name: "Cash App",
    logo: "https://logo.clearbit.com/cash.app",
    description:
      "Refer new users to Cash App and both earn bonuses. Popular with lifestyle and finance content creators.",
    commissionRange: "$5–$30 per referral",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://cash.app/refer",
    category: "finance",
    barrier: "open",
  },
  {
    id: "prog-acorns",
    name: "Acorns",
    logo: "https://logo.clearbit.com/acorns.com",
    description:
      "Micro-investing app that rounds up spare change. Strong with financial literacy and Gen Z money content.",
    commissionRange: "$5–$20 per signup",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.acorns.com/affiliate/",
    category: "finance",
    barrier: "approval",
  },
  {
    id: "prog-nerdwallet",
    name: "NerdWallet",
    logo: "https://logo.clearbit.com/nerdwallet.com",
    description:
      "Financial comparison platform for credit cards, loans, and insurance. High payouts on qualified leads.",
    commissionRange: "$15–$100+ per lead",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.nerdwallet.com/affiliate",
    category: "finance",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-robinhood",
    name: "Robinhood",
    logo: "https://logo.clearbit.com/robinhood.com",
    description:
      "Commission-free stock trading app. Refer new users and both receive free stock. Popular with fintok creators.",
    commissionRange: "Free stock per referral",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://robinhood.com/refer/",
    category: "finance",
    barrier: "open",
    isNew: true,
  },
  {
    id: "prog-coinbase",
    name: "Coinbase",
    logo: "https://logo.clearbit.com/coinbase.com",
    description:
      "Leading crypto exchange in the US. Earn commission on new user sign-ups and first trades.",
    commissionRange: "$10 per referral",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.coinbase.com/affiliates",
    category: "finance",
    barrier: "approval",
  },
  {
    id: "prog-sofi",
    name: "SoFi",
    logo: "https://logo.clearbit.com/sofi.com",
    description:
      "All-in-one finance app for banking, investing, and loans. Generous referral bonuses on new account sign-ups.",
    commissionRange: "$50–$100 per account",
    type: "ecommerce",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.sofi.com/refer/",
    category: "finance",
    barrier: "open",
  },

  // ── Brand Deal Marketplaces ─────────────────────────────────────────
  {
    id: "prog-collabstr",
    name: "Collabstr",
    logo: "https://logo.clearbit.com/collabstr.com",
    description:
      "Marketplace connecting creators with brands for paid collaborations. Set your own rates and get discovered by brands.",
    commissionRange: "Negotiable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.collabstr.com/",
    category: "fashion",
    barrier: "open",
  },
  {
    id: "prog-joinbrands",
    name: "JoinBrands",
    logo: "https://logo.clearbit.com/joinbrands.com",
    description:
      "Get paid $100–$400+ per UGC video. Brands send free products and pay for content creation. TikTok-first platform.",
    commissionRange: "$100–$400+ per UGC",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.joinbrands.com/",
    category: "fashion",
    barrier: "open",
    isNew: true,
  },
  {
    id: "prog-creator-hero",
    name: "Creator Hero",
    logo: "https://logo.clearbit.com/creatorhero.com",
    description:
      "Build your creator storefront and earn 20–50% commission on recommended products. No minimum followers required.",
    commissionRange: "20–50%",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.creatorhero.com/",
    category: "tech",
    barrier: "open",
  },
  {
    id: "prog-favikon",
    name: "Favikon",
    logo: "https://logo.clearbit.com/favikon.com",
    description:
      "AI-powered creator marketplace. Get matched with brands based on your content niche and audience demographics.",
    commissionRange: "Negotiable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.favikon.com/",
    category: "tech",
    barrier: "open",
  },
  {
    id: "prog-ltk",
    name: "LTK (LikeToKnowIt)",
    logo: "https://logo.clearbit.com/liketoknow.it",
    description:
      "Premium creator commerce platform. Share shoppable content and earn commissions from 7,000+ retail partners.",
    commissionRange: "Variable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://company.ltk.com/creators",
    category: "fashion",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-aspire",
    name: "Aspire (AspireIQ)",
    logo: "https://logo.clearbit.com/aspire.io",
    description:
      "Enterprise influencer marketing platform connecting creators with DTC and ecommerce brands for paid campaigns.",
    commissionRange: "Negotiable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.aspire.io/creator",
    category: "fashion",
    barrier: "approval",
  },
  {
    id: "prog-grin",
    name: "Grin",
    logo: "https://logo.clearbit.com/grin.co",
    description:
      "Creator management platform used by major DTC brands. Get discovered for paid collaborations and ambassador programs.",
    commissionRange: "Negotiable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://grin.co/creator-signup",
    category: "fashion",
    barrier: "approval",
  },
  {
    id: "prog-insense",
    name: "Insense",
    logo: "https://logo.clearbit.com/insense.pro",
    description:
      "UGC and creator marketplace connecting brands with content creators. Get paid for UGC, whitelisting, and ads.",
    commissionRange: "$100–$500+ per UGC",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://insense.pro/creator",
    category: "tech",
    barrier: "open",
    isNew: true,
  },
  {
    id: "prog-hashtag-paid",
    name: "#paid (Hashtag Paid)",
    logo: "https://logo.clearbit.com/hashtagpaid.com",
    description:
      "Opt-in creator marketplace where brands pitch you. Set your rates and choose campaigns that fit your brand.",
    commissionRange: "Negotiable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://hashtagpaid.com/creators",
    category: "tech",
    barrier: "approval",
  },
  {
    id: "prog-popular-pays",
    name: "Popular Pays",
    logo: "https://logo.clearbit.com/popularpays.com",
    description:
      "Lightricks-owned creator platform. Get hired for photo, video, and social content by brands and agencies.",
    commissionRange: "Negotiable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://popularpays.com/creators",
    category: "fashion",
    barrier: "open",
  },
  {
    id: "prog-shopmy",
    name: "ShopMy",
    logo: "https://logo.clearbit.com/shopmy.us",
    description:
      "Creator commerce platform for curating and sharing product recommendations. Earn commission from 1,000+ brands.",
    commissionRange: "10–25%",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://shopmy.us/join",
    category: "beauty",
    barrier: "approval",
    isFeatured: true,
  },
  {
    id: "prog-magiclinks",
    name: "MagicLinks",
    logo: "https://logo.clearbit.com/magiclinks.com",
    description:
      "Video commerce platform for creators. Auto-generate shoppable links from your content across YouTube, TikTok, and Instagram.",
    commissionRange: "Variable",
    type: "marketplace",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.magiclinks.com/creator",
    category: "tech",
    barrier: "approval",
  },

  // ── Affiliate Networks ──────────────────────────────────────────────
  {
    id: "prog-cj-affiliate",
    name: "CJ Affiliate",
    logo: "https://logo.clearbit.com/cj.com",
    description:
      "One of the largest affiliate networks with thousands of advertisers. Access brands across every category.",
    commissionRange: "5–20%",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.cj.com/",
    category: "tech",
    barrier: "open",
    hasLiveSearch: true,
  },
  {
    id: "prog-awin",
    name: "Awin / ShareASale",
    logo: "https://logo.clearbit.com/awin.com",
    description:
      "Global affiliate network with 25,000+ advertisers. $1 deposit to join. Access to major brands in fashion, tech, and more.",
    commissionRange: "5–15%",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.awin.com/",
    category: "fashion",
    barrier: "open",
  },
  {
    id: "prog-impact",
    name: "Impact.com",
    logo: "https://logo.clearbit.com/impact.com",
    description:
      "Partnership management platform used by Shopify, Uber, Airbnb, and more. Apply to individual brand programs.",
    commissionRange: "Variable",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.impact.com/",
    category: "tech",
    barrier: "approval",
  },
  {
    id: "prog-rakuten",
    name: "Rakuten Advertising",
    logo: "https://logo.clearbit.com/rakutenadvertising.com",
    description:
      "Premium affiliate network featuring top-tier brands. Higher barrier to entry but access to exclusive programs.",
    commissionRange: "1–20%",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://rakutenadvertising.com/",
    category: "fashion",
    barrier: "approval",
  },
  {
    id: "prog-clickbank",
    name: "ClickBank",
    logo: "https://logo.clearbit.com/clickbank.com",
    description:
      "Digital product marketplace with some of the highest commissions in affiliate marketing. Instant approval.",
    commissionRange: "5–75%",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.clickbank.com/",
    category: "tech",
    barrier: "open",
    isNew: true,
  },
  {
    id: "prog-flexoffers",
    name: "FlexOffers",
    logo: "https://logo.clearbit.com/flexoffers.com",
    description:
      "Affiliate network with 10,000+ advertisers across all verticals. Quick approval process for most programs.",
    commissionRange: "5–20%",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.flexoffers.com/",
    category: "tech",
    barrier: "approval",
  },
  {
    id: "prog-partnerstack",
    name: "PartnerStack",
    logo: "https://logo.clearbit.com/partnerstack.com",
    description:
      "B2B SaaS affiliate network featuring software partnerships. Earn recurring commissions on SaaS referrals.",
    commissionRange: "15–30% recurring",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://partnerstack.com/marketplace",
    category: "tech",
    barrier: "open",
    isNew: true,
  },
  {
    id: "prog-refersion",
    name: "Refersion",
    logo: "https://logo.clearbit.com/refersion.com",
    description:
      "Affiliate and influencer marketing platform for ecommerce brands. Join individual brand programs through their marketplace.",
    commissionRange: "Variable",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://www.refersion.com/marketplace",
    category: "fashion",
    barrier: "open",
  },
  {
    id: "prog-skimlinks",
    name: "Skimlinks",
    logo: "https://logo.clearbit.com/skimlinks.com",
    description:
      "Automatic affiliate link monetization across 48,000+ merchants. Turn any product mention into a commission opportunity.",
    commissionRange: "2–15%",
    type: "network",
    platforms: ["tiktok", "instagram"],
    signUpUrl: "https://skimlinks.com/publisher/signup/",
    category: "tech",
    barrier: "approval",
  },
];

// ---------------------------------------------------------------------------
// Converter: AffiliateProgram → BrandDeal
// ---------------------------------------------------------------------------

/**
 * Converts an AffiliateProgram entry into a BrandDeal so it can be
 * rendered alongside Virtuna-native deals in the same grid.
 */
export function affiliateProgramToDeal(program: AffiliateProgram): BrandDeal {
  return {
    id: program.id,
    brandName: program.name,
    brandLogo: program.logo,
    category: program.category,
    status: "active",
    commission: 0,
    payoutRange: program.commissionRange,
    startDate: new Date().toISOString(),
    description: program.description,
    isNew: program.isNew,
    isFeatured: program.isFeatured,
    source: "external",
    programType: program.type,
    signUpUrl: program.signUpUrl,
    platforms: program.platforms,
    barrier: program.barrier,
  };
}

/**
 * Returns all curated programs converted to BrandDeal format.
 */
export function getExternalDeals(): BrandDeal[] {
  return AFFILIATE_PROGRAMS.map(affiliateProgramToDeal);
}
