/**
 * FROZEN REAL ANALYSIS — generated by scripts/freeze-walkthrough-fixture.mts. Do not hand-edit.
 *
 * Source analysis: vSoTpo5AixUS  (tiktok_url, engine 3.21.0, 2026-07-24T22:27:25.393549+00:00)
 * Verified non-degraded at freeze time: 5 segments, 5 curve points,
 * craft signals present, transcript present, no ingest warnings.
 */

import type { BrainSnapshotInput } from "@/lib/surfaces/ambient-v2-brain";

/** Where attention falls FASTEST — the wall's moment. Derived from the curve, not chosen. */
export const FROZEN_LOSS_MOMENT = "0:12";
export const FROZEN_LOSS_LABEL = "Speaker contrasts the paid advice with free educational materials.";
/** The drop across that segment, in points of retained attention. */
export const FROZEN_LOSS_DELTA_PCT = 14;
/** True when attention never recovers — no local rebound anywhere in the clip. */
export const FROZEN_MONOTONIC_DECLINE = true;
/** Share still watching at the end, as the fold measured it. */
export const FROZEN_COMPLETION_PCT = 65;
export const FROZEN_SOURCE_ID = "vSoTpo5AixUS";

export const FROZEN_ANALYSIS: BrainSnapshotInput = {
  "stopPct": 35,
  "stimulusKey": "demo-vSoTpo5AixUS",
  "conceptLabel": "hook",
  "heatmap": {
    "segments": [
      {
        "idx": 0,
        "label": "Speaker introduces the core concept of scaling and pricing.",
        "t_end": 3,
        "t_start": 0,
        "is_hook_zone": true,
        "keyframe_uri": null
      },
      {
        "idx": 1,
        "label": "Speaker introduces the core concept of scaling and pricing.",
        "t_end": 5.5,
        "t_start": 3,
        "is_hook_zone": false,
        "keyframe_uri": null
      },
      {
        "idx": 2,
        "label": "Speaker provides an example involving weekly visitors and advisors.",
        "t_end": 11.5,
        "t_start": 5.5,
        "is_hook_zone": false,
        "keyframe_uri": null
      },
      {
        "idx": 3,
        "label": "Speaker contrasts the paid advice with free educational materials.",
        "t_end": 20.5,
        "t_start": 11.5,
        "is_hook_zone": false,
        "keyframe_uri": null
      },
      {
        "idx": 4,
        "label": "Speaker concludes with a summary of the 'litmus test'.",
        "t_end": 29,
        "t_start": 20.5,
        "is_hook_zone": false,
        "keyframe_uri": null
      }
    ],
    "personas": [],
    "weighted_curve": [
      0.7794871794871795,
      0.7438461538461538,
      0.6987179487179488,
      0.5608974358974357,
      0.47948717948717945
    ],
    "weights": {
      "fyp": 0.65,
      "niche": 0.2,
      "loyalist": 0.1,
      "cross_niche": 0.05
    },
    "weights_source": "default",
    "weighted_completion_pct": 0.6524871794871795
  },
  "videoSignals": {
    "pacing_score": 6,
    "hook_visual_impact": 7,
    "transition_quality": 4,
    "visual_production_quality": 5
  },
  "verbatim": {
    "hook": {
      "spoken_words": "Anything that scales, it's like great, I'll give it away for free.",
      "on_screen_text": "What you give away for free vs what you charge for"
    },
    "segments": [
      {
        "idx": 0,
        "spoken_text": "Anything that scales, it's like great, I'll give it away for free. If it doesn't scale, then I'm not.",
        "on_screen_text": "What you give away for free vs what you charge for | anything that | scales | I'll give it away | for free | if it doesn't scale | then I'm not"
      },
      {
        "idx": 1,
        "spoken_text": null,
        "on_screen_text": "What you give away for free vs what you charge for | anything that | scales | I'll give it away | for free | if it doesn't scale | then I'm not"
      },
      {
        "idx": 2,
        "spoken_text": "People come here every week. You know, we have whatever, 100 people who come in and my advisors who actually work my portfolio go and help them.",
        "on_screen_text": "people come here | every week | 100 people | who come in | and my advisors | who actually work | with my portfolio | go and help them"
      },
      {
        "idx": 3,
        "spoken_text": "That doesn't scale. So, you got to pay for that. But if you want all my books are free, all my courses are free, everything's free. My events are free, I have everything's free.",
        "on_screen_text": "that doesn't | scale | so | you gotta pay | for that | but | if you want- | all my books | are free | all my courses | are free | everything's | free | my events are free | i have | everything's free"
      },
      {
        "idx": 4,
        "spoken_text": "Mirroring that, like if it scales, it's free. If it doesn't scale, you have a price tag is a good litmus test for what you give versus what you charge for.",
        "on_screen_text": "mirroring that | if it's scales | it's free | if it doesn't scale | you have a | price tag | is a good | litmus test | for | what you give | vs | what you charge for"
      }
    ]
  }
};
