/**
 * Freeze a REAL analysis into the /go walkthrough's fixture.
 *
 *   npx tsx --env-file=.env.local scripts/freeze-walkthrough-fixture.mts <analysis_id> [outfile]
 *
 * The walkthrough's honesty floor (`docs/ONBOARDING-FUNNEL-DESIGN.md` §4) says the demo's analysis
 * must be real — run once through the real pipeline and frozen. This script is the "and frozen"
 * half: it reads a persisted `analysis_results` row and emits the exact `BrainSnapshotInput` the
 * walkthrough's adapters consume, so freezing is a paste rather than a transcription.
 *
 * It REFUSES a degraded row. A run whose scrape or vision stage failed still persists — it just
 * has no heatmap, no verbatim and no craft signals — and that is precisely the row you must not
 * ship as proof. (Learned the hard way: a `tiktok_url` run on 2026-07-24 completed, scored, and
 * carried `warnings: ["tiktok_url resolve/re-host unavailable [scrape_failed]"]` with every vision
 * signal false. It looked like a success from the outside.)
 *
 * Input mode does not matter — `video_upload` and `tiktok_url` produce the same columns. Only the
 * ingest differs, so an uploaded MP4 is just as real as a scraped URL, and needs no Apify.
 */

import { createClient } from "@supabase/supabase-js";
import { writeFileSync } from "fs";

interface HeatmapSegment {
  idx: number;
  t_start: number;
  t_end: number;
  label: string;
  is_hook_zone: boolean;
  keyframe_uri: string | null;
}

function fail(msg: string): never {
  console.error(`\n✗ ${msg}\n`);
  process.exit(1);
}

async function main() {
  const id = process.argv[2];
  const outfile = process.argv[3] ?? "src/components/offer/walkthrough/frozen-analysis.ts";
  if (!id) fail("usage: freeze-walkthrough-fixture.mts <analysis_id> [outfile]");

  const db = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );

  const { data, error } = await db.from("analysis_results").select("*").eq("id", id).maybeSingle();
  if (error) fail(`query failed: ${error.message}`);
  if (!data) fail(`no analysis row with id ${id}`);

  const row = data as Record<string, unknown>;
  const heatmap = (row.heatmap ?? {}) as Record<string, unknown>;
  const verbatim = (row.verbatim ?? {}) as Record<string, unknown>;
  const variants = (row.variants ?? {}) as Record<string, unknown>;
  const craft = (variants.craft ?? {}) as Record<string, unknown>;
  const videoSignals = craft.video_signals as Record<string, number> | undefined;
  const segments = (heatmap.segments ?? []) as HeatmapSegment[];
  const curve = (heatmap.weighted_curve ?? []) as number[];
  const warnings = (row.warnings ?? []) as string[];

  // ── refuse anything that would ship as fabricated proof ────────────────────────────────────
  const problems: string[] = [];
  if (!segments.length) problems.push("heatmap.segments is empty — no vision pass, nothing to scrub");
  if (!curve.length) problems.push("heatmap.weighted_curve is empty — no measured attention curve");
  if (!videoSignals) problems.push("variants.craft.video_signals missing — no craft score to show");
  if (!((verbatim.segments as unknown[] | undefined)?.length)) {
    problems.push("verbatim.segments is empty — no transcript for the scrubber");
  }
  if (warnings.some((w) => /scrape_failed|re-host unavailable/i.test(w))) {
    problems.push(`ingest degraded: ${warnings.find((w) => /scrape_failed/i.test(w))}`);
  }
  if (problems.length) {
    console.error(`\n✗ ${id} is a DEGRADED run and must not be frozen as proof:\n`);
    problems.forEach((p) => console.error(`   • ${p}`));
    console.error(`\n   score=${row.overall_score} confidence=${row.confidence} (${row.confidence_label})`);
    console.error(`   signal_availability=${JSON.stringify(row.signal_availability)}\n`);
    process.exit(1);
  }

  // The wall's moment is the steepest DROP, not the lowest point.
  //
  // On a monotonically declining curve — which is what a real short-form video usually produces —
  // the lowest point is always the last segment, which is trivially true and says nothing. What the
  // viewer actually experiences as "where I left" is the segment attention falls FASTEST into.
  // Derived from the measured curve, never authored.
  let steepest = 1;
  let worstDelta = 0;
  for (let i = 1; i < curve.length; i++) {
    const delta = curve[i] - curve[i - 1];
    if (delta < worstDelta) {
      worstDelta = delta;
      steepest = i;
    }
  }
  const dipSegment = segments[steepest] ?? segments[segments.length - 1];
  const lowestIdx = curve.reduce((lo, v, i) => (v < curve[lo] ? i : lo), 0);
  const stamp = (t: number) => `0:${String(Math.round(t)).padStart(2, "0")}`;
  const monotonic = curve.every((v, i) => i === 0 || v <= curve[i - 1]);

  const module = `/**
 * FROZEN REAL ANALYSIS — generated by scripts/freeze-walkthrough-fixture.mts. Do not hand-edit.
 *
 * Source analysis: ${id}  (${row.input_mode}, engine ${row.engine_version}, ${row.created_at})
 * Verified non-degraded at freeze time: ${segments.length} segments, ${curve.length} curve points,
 * craft signals present, transcript present, no ingest warnings.
 */

import type { BrainSnapshotInput } from "@/lib/surfaces/ambient-v2-brain";

/** Where attention falls FASTEST — the wall's moment. Derived from the curve, not chosen. */
export const FROZEN_LOSS_MOMENT = ${JSON.stringify(stamp(dipSegment.t_start))};
export const FROZEN_LOSS_LABEL = ${JSON.stringify(dipSegment.label)};
/** The drop across that segment, in points of retained attention. */
export const FROZEN_LOSS_DELTA_PCT = ${Math.round(Math.abs(worstDelta) * 100)};
/** True when attention never recovers — no local rebound anywhere in the clip. */
export const FROZEN_MONOTONIC_DECLINE = ${monotonic};
/** Share still watching at the end, as the fold measured it. */
export const FROZEN_COMPLETION_PCT = ${Math.round(Number(heatmap.weighted_completion_pct ?? 0) * 100)};
export const FROZEN_SOURCE_ID = ${JSON.stringify(id)};

export const FROZEN_ANALYSIS: BrainSnapshotInput = ${JSON.stringify(
    {
      stopPct: Math.round(100 - (Number(heatmap.weighted_completion_pct ?? 0) * 100)),
      stimulusKey: `demo-${id}`,
      conceptLabel: "hook",
      heatmap: {
        segments,
        personas: [],
        weighted_curve: curve,
        weights: heatmap.weights,
        weights_source: heatmap.weights_source,
        weighted_completion_pct: heatmap.weighted_completion_pct,
      },
      videoSignals,
      verbatim,
    },
    null,
    2,
  )};
`;

  writeFileSync(outfile, module);

  console.log(`\n✓ froze ${id} → ${outfile}`);
  console.log(`   mode        : ${row.input_mode}   engine ${row.engine_version}`);
  console.log(`   segments    : ${segments.length}   curve points: ${curve.length}`);
  console.log(`   craft       : ${JSON.stringify(videoSignals)}`);
  console.log(`   curve       : [${curve.map((v) => v.toFixed(2)).join(", ")}]${monotonic ? "  (monotonic decline — never recovers)" : ""}`);
  console.log(`   steepest drop: ${stamp(dipSegment.t_start)} — -${Math.round(Math.abs(worstDelta) * 100)}pts — "${dipSegment.label}"`);
  console.log(`   lowest point : ${stamp(segments[lowestIdx].t_start)} (${Math.round(curve[lowestIdx] * 100)}% still watching)`);
  console.log(`   keyframes   : ${segments.filter((s) => s.keyframe_uri).length}/${segments.length} have a still`);
  console.log(`\n   Next: point walkthrough-fixture.ts at FROZEN_ANALYSIS, write the two insight`);
  console.log(`   payloads from this run's real output, then flip WALKTHROUGH_IS_PLACEHOLDER.\n`);
}

main().catch((e) => fail((e as Error).message));
