/**
 * regen-kc.ts — Generative Knowledge-Core compiler.
 *
 * Reads .planning/corpus/*.md (the prose SSOT) and writes src/lib/kc/compiled.ts,
 * a byte-stable TypeScript constants module.
 *
 * BYTE-STABILITY CONTRACT: this script produces deterministic output.
 * — No Date.now(), Math.random(), or per-request data in the output.
 * — Re-running on unchanged .md input produces byte-identical compiled.ts.
 * — The escape rule (backslash → \\, backtick → \`, ${ → \${) mirrors apollo-core.ts:4-6.
 *
 * Usage: npx tsx scripts/regen-kc.ts
 * Run after any change to .planning/corpus/*.md.
 *
 * Source patterns:
 *   scripts/build-corpus.ts:1-8  (dotenv + tsconfig-paths runner pattern)
 *   src/lib/engine/apollo-core.ts:4-6  (escape rule)
 *   src/lib/engine/apollo-core.ts:21-33  (BYTE-STABILITY CONTRACT verbiage)
 *   src/lib/engine/apollo-core.ts:254  (compile-time constant concat pattern)
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

// ─── Escape rule (mirrors apollo-core.ts:4-6) ───────────────────────────────
// Escape backslash first (must come before the others), then backtick, then ${.
// This removes the lockstep-drift hazard documented at apollo-core.ts:26 by
// making the copy step a script rather than a manual operation.
export function escapeForTemplate(md: string): string {
  return md
    .replace(/\\/g, "\\\\")   // \ → \\  (must be first)
    .replace(/`/g, "\\`")     // ` → \`
    .replace(/\$\{/g, "\\${"); // ${ → \${
}

// ─── Paths ───────────────────────────────────────────────────────────────────
const ROOT   = resolve(__dirname, "..");
const CORPUS = resolve(ROOT, ".planning/corpus");
const OUT    = resolve(ROOT, "src/lib/kc/compiled.ts");

// ─── Read + escape corpus files ──────────────────────────────────────────────
const base   = escapeForTemplate(readFileSync(resolve(CORPUS, "base.md"),   "utf-8"));
const ideas  = escapeForTemplate(readFileSync(resolve(CORPUS, "ideas.md"),  "utf-8"));
const hooks  = escapeForTemplate(readFileSync(resolve(CORPUS, "hooks.md"),  "utf-8"));
const chat   = escapeForTemplate(readFileSync(resolve(CORPUS, "chat.md"),   "utf-8"));
const script = escapeForTemplate(readFileSync(resolve(CORPUS, "script.md"), "utf-8"));

// ─── Generate compiled.ts ────────────────────────────────────────────────────
// The per-mode system prompts are assembled at COMPILE TIME (D-03, Open Q2):
// base + separator + slice → one byte-stable string fixed in source.
// This is the strictest form of the byte-stability contract.
const output = `\
// GENERATED by scripts/regen-kc.ts — do not hand-edit. Source: .planning/corpus/*.md
//
// BYTE-STABILITY CONTRACT: every export here is a build-time constant string with
// NO runtime interpolation (no timestamps, random values, or per-request data). It is
// safe to embed via template literal in a cache-stable prefix — the result stays
// byte-identical across requests, preserving Qwen automatic input-cache hits.
// This module is decoupled from the scoring engine — it does NOT import
// KNOWLEDGE_CORE or APOLLO_SYSTEM_PROMPT (D-08 greenfield).
//
// To regenerate: edit .planning/corpus/*.md, then run: npx tsx scripts/regen-kc.ts

// ─── Raw per-mode constants ───────────────────────────────────────────────────

/** Generative BASE — domain-general craft intelligence (D-00 north star). */
export const KC_BASE = \`${base}\`;

/** Ideas SLICE — points BASE at TikTok/Reels/Shorts idea-concept generation. */
export const KC_IDEAS_SLICE = \`${ideas}\`;

/** Hooks SLICE — points BASE at TikTok/Reels/Shorts hook-line generation. */
export const KC_HOOKS_SLICE = \`${hooks}\`;

/** Chat SLICE — thin stance-slice for open conversational mode (BASE-heavy; D-14). */
export const KC_CHAT_SLICE = \`${chat}\`;

/** Script SLICE — points BASE at TikTok/Reels/Shorts beat-structured script generation. */
export const KC_SCRIPT_SLICE = \`${script}\`;

// ─── Compile-time assembled per-mode system prompts (D-03) ───────────────────
// Each is a byte-stable system prompt: BASE + separator + SLICE, assembled at
// compile time so the byte-stable string is fixed in source.
// Only the live-grounding user message varies per request (D-03 two-tier cache).

/** Ideas system prompt — byte-stable per-mode prefix (base + ideas slice). */
export const KC_IDEAS_SYSTEM_PROMPT = \`\${KC_BASE}\\n\\n---\\n\\n\${KC_IDEAS_SLICE}\`;

/** Hooks system prompt — byte-stable per-mode prefix (base + hooks slice). */
export const KC_HOOKS_SYSTEM_PROMPT = \`\${KC_BASE}\\n\\n---\\n\\n\${KC_HOOKS_SLICE}\`;

/** Chat system prompt — byte-stable per-mode prefix (base + chat slice). */
export const KC_CHAT_SYSTEM_PROMPT = \`\${KC_BASE}\\n\\n---\\n\\n\${KC_CHAT_SLICE}\`;

/** Script system prompt — byte-stable per-mode prefix (base + script slice). */
export const KC_SCRIPT_SYSTEM_PROMPT = \`\${KC_BASE}\\n\\n---\\n\\n\${KC_SCRIPT_SLICE}\`;
`;

// ─── Write output ─────────────────────────────────────────────────────────────
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, output, "utf-8");

console.log(`[regen-kc] compiled.ts written → ${OUT}`);
