import type { Niche } from "./eval-config";
import { NICHE_THRESHOLDS } from "./eval-config";

/** corpus_version identifier — D-12 semver-style. */
export type CorpusVersion = `${"pilot" | "full"}.${string}`;

export interface NicheThresholds {
  viralFloor: number; // ≥ → viral (D-10 hard cutoff)
  underCeiling: number; // ≤ → under
}

export type ThresholdsByNiche = Record<Niche, NicheThresholds>;

/**
 * Threshold snapshots — one entry per corpus_version.
 * Add new entries; NEVER edit existing ones (D-13 immutability).
 *
 * Plan F (pilot retrospective) appends the empirically-recalibrated
 * "full.YYYY-MM-DD" entry; Phase 1 ships only the pilot snapshot.
 */
const THRESHOLD_SNAPSHOTS: Record<string, ThresholdsByNiche> = {
  "pilot.2026-05-12": NICHE_THRESHOLDS,
  // ──────────────────────────────────────────────────────────────────────
  // Empirically calibrated from full.2026-05-11 raw scrape distributions (D-09).
  // Generated by scripts/calibrate-thresholds.ts on 2026-05-11.
  // Source: 568-row clockworks scrape → 180-day recency filter → 238-row
  //         filtered cache → P80 (viralFloor) / P40 (underCeiling) per niche.
  // See .planning/cache/raw-full.2026-05-11.filtered.jsonl + retrospective.
  // Comedy separation (2.88×) is below the 3× sanity floor — accepted as
  // genuine distribution compression in trending comedy hashtags, not a
  // calibration error. Documented in 01-F-PILOT-RETROSPECTIVE.md.
  // Sealed per D-13 — IMMUTABLE once committed.
  // ──────────────────────────────────────────────────────────────────────
  "full.2026-05-11": {
    beauty:    { viralFloor:  5_120_000, underCeiling:   250_840 },
    fitness:   { viralFloor:  5_480_000, underCeiling: 1_164_240 },
    edu:       { viralFloor:  2_000_000, underCeiling:   368_500 },
    comedy:    { viralFloor: 25_900_000, underCeiling: 9_000_000 },
    lifestyle: { viralFloor:    871_200, underCeiling:   153_540 },
  },
};

export function getThresholds(
  version: CorpusVersion | string,
): ThresholdsByNiche {
  const snap = THRESHOLD_SNAPSHOTS[version];
  if (!snap) {
    throw new Error(
      `Unknown corpus_version: ${version}. Add a snapshot to THRESHOLD_SNAPSHOTS before evaluating.`,
    );
  }
  return snap;
}

/** Test/debug helper — lists all known versions. NOT for production code. */
export function listKnownVersions(): string[] {
  return Object.keys(THRESHOLD_SNAPSHOTS);
}
