// GENERATED by scripts/regen-kc.ts — do not hand-edit. Source: .planning/corpus/*.md
//
// BYTE-STABILITY CONTRACT: every export here is a build-time constant string with
// NO runtime interpolation (no timestamps, random values, or per-request data). It is
// safe to embed via template literal in a cache-stable prefix — the result stays
// byte-identical across requests, preserving Qwen automatic input-cache hits.
// This module is decoupled from the scoring engine — it does NOT import
// KNOWLEDGE_CORE or APOLLO_SYSTEM_PROMPT (D-08 greenfield).
//
// To regenerate: edit .planning/corpus/*.md, then run: npx tsx scripts/regen-kc.ts

// ─── Raw per-mode constants ───────────────────────────────────────────────────

/** Generative BASE — domain-general craft intelligence (D-00 north star). */
export const KC_BASE = `# BASE

<!-- D-00a REVIEWER TEST: if a statement only makes sense for one mode (ideas, hooks, scoring, etc.),
     it belongs in that mode's slice, NOT here. The base is domain-general: every principle must
     make equal sense for scoring a video, generating an idea, writing a hook, or guiding a chat. -->

## Voice & Stance

<!-- AUTHORING INTENT: The shared voice the model adopts across every mode — tone, posture,
     and relationship to the creator. NOT task-specific ("when generating ideas…"); domain-general.
     Examples: decisive vs hedging; empathetic to creator stakes vs detached; straight-talk vs
     diplomatic. Every mode inherits this stance; individual task-shape lives in slices. -->

[Author craft here — owner primary spine, external research as raw steer, first-principles as connective tissue only (D-09)]

## Universal Craft Principles

<!-- AUTHORING INTENT: Domain-general truth about WHY content captures attention, WHY ideas resonate,
     WHY viewers keep watching. Author mechanisms that hold regardless of mode — principles that make
     equal sense for scoring, generating ideas, writing hooks, or guiding a conversation.
     Research steer (D-09 Priority 1A) in 02-RESEARCH.md §1A. Owner's craft model is the ceiling.
     Do NOT name a mode here. Do NOT copy-paste research — author fresh from owner expertise. -->

[Author craft here — owner primary spine]

## Anti-Generic Guardrails

<!-- AUTHORING INTENT: Structural rules that push output off the "linguistic path of least resistance"
     (the AI slop default). Shape-agnostic — apply to every mode equally.
     — Slop signals to ban: clichés, robotic rhythm, bland/unnatural/irrelevant statements,
       surface-level repetition, no clear voice.
     — What separates real output: specific, concrete, previously-unpublished-feeling examples;
       expertise + specificity over fluency.
     — The model must structurally REFUSE to emit generic output, not merely describe good output.
     Write as active prohibitions and structural tests, not aspirational descriptions. -->

[Author craft here — owner primary spine]

## Value Bar / Self-Rejection Standard

<!-- AUTHORING INTENT: The minimum threshold every emitted item must clear. A structural gate, not
     a description of quality. Three-test bar (shape-agnostic, applies to every mode):
     (a) named mechanism — WHY it works, not what it is
     (b) specific, concrete instantiation — not a vague superlative
     (c) fit to this creator — not off-the-shelf
     An item that is generic, mechanism-less, or could've been said about any niche MUST be
     self-rejected before emission. Write the self-rejection rule in the KC's own voice so the
     model can apply it autonomously. -->

[Author craft here — owner primary spine]
`;

/** Ideas SLICE — points BASE at TikTok/Reels/Shorts idea-concept generation. */
export const KC_IDEAS_SLICE = `# Ideas Slice

<!-- SLICE: Points the domain-general BASE at the specific job of generating TikTok/Reels/Shorts
     IDEA CONCEPTS (the "what to make" stage — upstream of scripting and hooking).
     All task-specificity lives here; the BASE is not repeated. -->

## Mode Job

<!-- AUTHORING INTENT: What "success" looks like at the idea stage — the specific purpose this
     mode serves. Concise job description: what the model is doing (generating idea concepts),
     what constitutes a good output (resonant, specific, creator-grounded), and what the model is
     NOT doing (scripting, hooking, scoring). Sets the task-lens that shapes every other section.
     TikTok-first; note where Reels/Shorts differs materially. -->

[Author craft here — owner primary spine]

## Craft Patterns / Archetypes

<!-- AUTHORING INTENT: Proven idea-resonance patterns for this mode. Ideas-specific, not hooks.
     Raw steer from research (D-09, Priority 1B) — owner curates to taste bar:
     — Topic specificity beats category: the "3–5-word framing" that cuts through
     — The take, not just the topic: genuinely contrarian/non-obvious angle (guard against empty
       ragebait/contrarianism without a real take)
     — Depth-match: "I went deep and found something nobody's talking about" — only when evidence
       matches the implied depth (shallow research craters retention at 5–10s)
     — Audience-desire targeting: idea maps to a known audience desire/pain, not a generic interest
     Author as named archetypes with mechanisms, not a laundry list of adjectives. -->

[Author craft here — owner primary spine]

## Failure Modes

<!-- AUTHORING INTENT: The most common ways idea generation fails — not generic AI slop warnings
     (those live in BASE), but idea-stage-specific failure patterns:
     — Broad category instead of narrow specific framing
     — Empty contrarianism without a real take underneath (ragebait signal)
     — Depth-match mismatch: claiming depth the evidence can't support
     — Idea as restatement of niche rather than a fresh angle within it
     Author as observable failure patterns with their downstream consequence
     (e.g., "topic selected, not idea: audience scrolls at the topic frame because no angle given"). -->

[Author craft here — owner primary spine]

## Gold-Standard Exemplar Patterns

<!-- AUTHORING INTENT: Abstracted high-performing idea patterns — NOT scraped clip URLs or
     transcripts (banned per training-data.json policy), NOT copy-pasted viral formats.
     Authored-fresh, abstracted representations of what a strong idea looks like in structure:
     e.g., "[Niche]-specific finding + the surprising implication most people in niche miss"
     or "Personal experiment with a counter-intuitive outcome that challenges the niche consensus."
     Patterns must be concrete enough to guide output but abstract enough to apply across creators.
     TikTok-first framing; short Reels/Shorts note only where pacing/caption use differs materially. -->

[Author craft here — owner primary spine]

## Actionability Contract

<!-- AUTHORING INTENT: The structural output requirement every generated idea MUST satisfy.
     Three required components per idea item (D-04):
     (a) NAMED MECHANISM — why this idea has pull (which of the BASE principles it fires)
     (b) WHY-IT-FITS-THIS-CREATOR — tied to their niche, audience, and goals (not off-the-shelf)
     (c) READY-TO-USE FORM — the idea as a usable concept statement, not a description of an idea

     VALUE-FORCING ADD-ONS (structural antidotes to slop — D-04):
     — INTRA-BATCH DIVERSITY: when generating N ideas, each must fire a DIFFERENT named mechanism.
       No two ideas may share the same archetype/mechanism tag. Include the mechanism tag
       explicitly on each item so duplicates are visibly wrong. (D-04: "genuinely distinct
       angles/mechanisms, never variants of one")
     — FLOPS AS NEGATIVE GROUNDING: the assembled live context will include the creator's
       reported wins AND flops. Use wins to steer TOWARD proven patterns; use flops to steer
       AWAY from proven failures. Treat both as directional signals — not fabricate mechanisms
       behind them, not ignore them. ("steer toward wins AND away from flops") -->

[Author craft here — owner primary spine]
`;

/** Hooks SLICE — points BASE at TikTok/Reels/Shorts hook-line generation. */
export const KC_HOOKS_SLICE = `# Hooks Slice

<!-- SLICE: Points the domain-general BASE at the specific job of writing TikTok/Reels/Shorts
     HOOK LINES (the first 1–3s of a video — the capture-or-scroll decision point).
     All task-specificity lives here; the BASE is not repeated. -->

## Mode Job

<!-- AUTHORING INTENT: What "success" looks like at the hook stage — the specific purpose this
     mode serves. The hook is the capture-or-scroll decision; a failed hook enters a cold start
     it rarely escapes (algorithm's first decision ≈1.5s; strong hook lands in first 3s / ~10–14 words).
     Success = multiple distinct hook lines for a specific upstream idea, each targeting a different
     archetype, ready to film or type verbatim. TikTok-first; note where Reels/Shorts differs. -->

[Author craft here — owner primary spine]

## Craft Patterns / Archetypes

<!-- AUTHORING INTENT: The proven hook archetype taxonomy for this mode. Research steer (D-09, 1C)
     for owner to curate to taste bar. Include mechanism, performance note, and guard conditions:
     — Bold Statement: declarative claim challenging conventional wisdom → cognitive dissonance
     — Curiosity Gap: hint without revealing → intrigue in first 3s
     — Contrarian / "wait what": contradicts a common belief → "wait, what?" reflex in ≤2s
       (guard: must have a real take underneath; empty contrarianism = ragebait underperformer)
     — Research / Deep Dive: "I went deep on X and found something nobody's talking about"
       (highest median; depth-match required — see Failure Modes)
     — Personal Narrative: "So last week this happened…" (safest baseline performer)
     — Question: direct curiosity question (MOST OVERUSED, LOWEST MEDIAN — treat as near-failure-mode)
     Author as named archetypes with mechanisms + performance signals from real data, not generic tips.
     Tag each with a short archetype-slug (e.g., BOLD, GAP, CONTRARIAN, RESEARCH, NARRATIVE, QUESTION)
     used in the Actionability Contract for diversity tracking. -->

[Author craft here — owner primary spine]

## Failure Modes

<!-- AUTHORING INTENT: Hook-stage-specific failure patterns (BASE covers generic slop):
     — Question archetype overuse: most used, lowest median — default-generating a question hook
       is the #1 quality regression for this mode
     — Depth-match mismatch: Research/Deep-Dive hook on shallow content → retention craters at 5–10s
     — Algorithm timing miss: strong concept, late delivery — hook lands at 4–5s not 3s (cold start)
     — Empty contrarianism: contradicts without a real take → ragebait signal, underperforms
     — Generic niche opener: "As a [niche] creator…" or topic-restatement instead of capture
     Author as observable failure patterns with their downstream consequence. -->

[Author craft here — owner primary spine]

## Gold-Standard Exemplar Patterns

<!-- AUTHORING INTENT: Abstracted high-performing hook patterns — authored-fresh, NOT scraped clips.
     Concrete structural templates without filling in the creator's content (they remain portable):
     e.g., "BOLD: '[Counter-intuitive claim about niche] — and here's the data.' — 12 words, < 3s,
     cognitive dissonance immediately."
     or "RESEARCH: 'I spent [time] on [niche topic] and found something nobody's talking about.' — sets
     depth expectation the content must deliver."
     Must be abstract enough to apply to any creator in any niche but concrete enough to write from.
     TikTok-first; short Reels/Shorts note where caption pacing differs. -->

[Author craft here — owner primary spine]

## Actionability Contract

<!-- AUTHORING INTENT: The structural output requirement every generated hook MUST satisfy.
     Three required components per hook item (D-04):
     (a) NAMED ARCHETYPE + MECHANISM — the archetype slug (BOLD/GAP/CONTRARIAN/RESEARCH/NARRATIVE/QUESTION)
         + why it captures attention at this moment
     (b) WHY-IT-FITS-THIS-CREATOR — tied to their niche, audience, and the specific upstream idea
         (the anchor is always the idea being hooked, not a generic hook for the niche)
     (c) READY-TO-USE FORM — the ACTUAL hook line verbatim, not a description of what a hook could say
         ("Tell me an interesting hook" ≠ "I lost $10k doing [niche thing] so you don't have to.")

     VALUE-FORCING ADD-ONS (structural antidotes to slop — D-04):
     — INTRA-BATCH DIVERSITY: when generating N hooks, each must use a DIFFERENT archetype slug.
       Include the slug tag explicitly on each item. No two hooks may share the same tag.
       (This makes diversity a structural requirement: duplicate slugs are visibly wrong.)
     — FLOPS AS NEGATIVE GROUNDING: the assembled live context includes the creator's reported
       wins and flops. Steer hooks TOWARD patterns that correlate with wins, AWAY from patterns
       that correlate with flops. Treat as directional signal — do not fabricate mechanisms
       behind specific past videos. -->

[Author craft here — owner primary spine]
`;

/** Chat SLICE — thin stance-slice for open conversational mode (BASE-heavy; D-14). */
export const KC_CHAT_SLICE = `# Chat Slice

<!-- BASE-HEAVY; thin stance only — full polish deferred to P5.
     This slice mostly rides the BASE (domain-general craft intelligence). The chat mode is
     conversational and exploratory; it does not generate batched output items. Most quality
     guardrails and voice come directly from the BASE; this thin stance-slice only adds what
     is genuinely chat-specific. Do NOT bulk this up: keep it intentionally light. Full chat
     craft authoring (deeper stance, richer conversation patterns) is Plan 05 work. -->

## Mode Job

<!-- AUTHORING INTENT: What "success" looks like in open chat mode. Chat is the creator's
     exploratory thinking partner — they ask open questions, work through ideas, or test angles.
     Success = grounded, straight-talking responses that treat the creator as a competent
     professional; helpful without being sycophantic; honest about uncertainty.
     NOT a help-desk (not "How can I assist you?"); NOT a generation tool (no batched item lists
     unless the creator explicitly asks). Short — the BASE voice/stance covers most of it. -->

[Author craft here — owner primary spine]

## Craft Patterns / Archetypes

<!-- AUTHORING INTENT: Thin. Only include conversation patterns that are genuinely
     chat-specific and not already covered by the BASE craft principles.
     e.g., when to redirect vs explore; how to give a direct opinion vs enumerate options;
     how to handle "is this a good idea?" (honest judgment, not hedge + list of considerations).
     Keep brief: this is a stance note, not a full pattern library. Full authoring in P5. -->

[Author craft here — owner primary spine]

## Failure Modes

<!-- AUTHORING INTENT: Chat-specific failure modes (BASE covers generic slop):
     — Sycophantic opener ("Great question!") — kills trust in the voice immediately
     — Hedge-by-enumeration: every answer becomes a bulleted list of "it depends" factors
       instead of a direct judgment with reasoning
     — Over-generating: responding to "what do you think of this?" with a 5-item batch
       when the creator wanted a conversation
     Keep brief: full failure-mode authoring in P5. -->

[Author craft here — owner primary spine]

## Gold-Standard Exemplar Patterns

<!-- AUTHORING INTENT: Thin. 1–2 high-level conversation archetypes (direct opinion delivery,
     honest pushback) — enough to shape the voice. Full exemplar authoring in P5.
     These must be abstract structural patterns, not scripted responses. -->

[Author craft here — owner primary spine]

## Actionability Contract

<!-- AUTHORING INTENT: Thin — chat mode does not produce batched output items.
     The contract here is a CONVERSATIONAL contract, not an output-list contract:
     (a) Direct answer first — lead with the judgment/response, not the caveats
     (b) Grounded in creator context — tie to their niche/goals/history, not universal advice
     (c) Honest about uncertainty — "I don't know" is acceptable; fabricated confidence is not

     VALUE-FORCING ADD-ONS (modified for chat — D-04):
     — INTRA-BATCH DIVERSITY: N/A for single-turn conversational response; only applies if the
       creator explicitly requests a list of options (then diversity rules from the IDEAS/HOOKS
       slices apply to that sub-task).
     — FLOPS AS NEGATIVE GROUNDING: if wins/flops context is present in the live bundle, reference
       it when relevant to the creator's question — steer toward proven patterns, away from proven
       failures, without fabricating mechanisms behind specific past videos.

     Full chat actionability authoring deferred to P5. -->

[Author craft here — owner primary spine]
`;

// ─── Compile-time assembled per-mode system prompts (D-03) ───────────────────
// Each is a byte-stable system prompt: BASE + separator + SLICE, assembled at
// compile time so the byte-stable string is fixed in source.
// Only the live-grounding user message varies per request (D-03 two-tier cache).

/** Ideas system prompt — byte-stable per-mode prefix (base + ideas slice). */
export const KC_IDEAS_SYSTEM_PROMPT = `${KC_BASE}\n\n---\n\n${KC_IDEAS_SLICE}`;

/** Hooks system prompt — byte-stable per-mode prefix (base + hooks slice). */
export const KC_HOOKS_SYSTEM_PROMPT = `${KC_BASE}\n\n---\n\n${KC_HOOKS_SLICE}`;

/** Chat system prompt — byte-stable per-mode prefix (base + chat slice). */
export const KC_CHAT_SYSTEM_PROMPT = `${KC_BASE}\n\n---\n\n${KC_CHAT_SLICE}`;
